### ISSUE TITLE
Plugin cause other UI framework styles to fail to package

### ISSUE THREAD

**Issue by StringKe** [forsartis/vue-cli-plugin-tailwind#11]
Looks like there are some problems?
![image](https://user-images.githubusercontent.com/31089228/74800114-76bd0200-530d-11ea-8f2b-e5c3ab3c822f.png)
![image](https://user-images.githubusercontent.com/31089228/74800254-dfa47a00-530d-11ea-9c47-cb590d85825c.png)
![image](https://user-images.githubusercontent.com/31089228/74800312-0662b080-530e-11ea-8c07-eb41c46f9d7d.png)

look this repo: [REPO](https://github.com/StringKe/test.git)
I'm using a ui framework to work with tailwindcss, everything is working properly under `yarn run serve`, part of the css file will be lost after `yarn run build`

**Comment by forsartis** [comment]
PurgeCSS removes unused CSS. The ant styles are stripped out because their usage is hidden inside the `node_modules` directory.

To fix this you can tell PurgeCSS to ignore the ant design CSS.
In your `src/antd-variables.less` file add these comments:
```less
/* purgecss start ignore */
@import '~ant-design-vue/dist/antd.less';
/* purgecss end ignore */
```
