### ISSUE TITLE
Autoprefixer is not added to postcss.config.js on install

### ISSUE THREAD

**Issue by stefano-b** [forsartis/vue-cli-plugin-tailwind#14]
After running `vue add tailwind`, the generated `postcss.config.js` does not cointain an entry for Autporefixer, like stated on the Readme.

Its contents are as follows: 
```
module.exports = {
  plugins: {
    tailwindcss: {},
    'vue-cli-plugin-tailwind/purgecss': {}
  }
}
```

**Comment by forsartis** [comment]
Yeah that’s right. Autoprefixer is added internally in vue-cli since v4.1.0 https://github.com/vuejs/vue-cli/pull/4798. I will update the readme.

**Comment by stefano-b** [comment]
I've done a little testing, and you are right: Autoprefixer seems to be automatically added in to the build process by Vue CLI.

**Anyway, this seem to work as a default only if no `postcss.config.js` is present in the project root folder**; if such file is present, I can only get the correct vendor prefixes after the build process if Autoprefixer is explicitly called into it.

Basically, my `postcss.config.js` file should be set like you described in the documentation, with an `autoprefixer: {}` line after the tailwind ones. 

I suppose that this is working as intended (so, I don't think that it's a bug), probably the rationale is to have generic default settings while still leaving to the user the ability to manually change them; maybe it could be useful to ask directly to Vue CLI devs to have a confirmation about this .

Anyway, the fact is that if I include a `postcss.config.js` into my project, I need to explicitly include an Autprefixer to make it work as intended.

**Comment by forsartis** [comment]
Okay makes sense, providing your own `postcss.config.js` will overwrite Vue CLI’s internal one. 
In that case, it would be best to add autoprefixer back in, because people expect that it is enabled by default.
Thanks for testing this out.
