### ISSUE TITLE
Updating Tailwind version

### ISSUE THREAD

**Issue by malydok** [forsartis/vue-cli-plugin-tailwind#17]
Hello, thanks for creating the plugin, works great.

Is it possible for us users to upgrade the Tailwind version ourselves or do you have to bump the plugin to achieve that?

Current `tailwindcss` is 1.6.0, plugin is 1.4.5.

#16 is pending for a bit now.

**Comment by forsartis** [comment]
Hello, you will get Tailwind CSS v.1.6.0 when you run `npm update` (or `yarn upgrade`).
The tailwindcss dependency is set to a range `^1.4.5` (>=1.4.5 <2.0.0). So until there is a major version update, you should get the latest version of Tailwind.
