### ISSUE TITLE
Plans for v1.0.0 compatibly 

### ISSUE THREAD

**Issue by mikeerickson** [forsartis/vue-cli-plugin-tailwind#2]
Do you have any short term plans for updating this package to match changes in Tailwind 1.0

**Comment by forsartis** [comment]
Yes, I will update to Tailwind 1.0 once it's officially released,
might do a pre-release this week to test things out.

**Comment by mikeerickson** [comment]
If you chose to go that route, I would be willing to give it a run through.

**Comment by forsartis** [comment]
I released a beta version.
See https://github.com/forsartis/vue-cli-plugin-tailwind/releases/tag/v1.0.0-beta.1 for installation instructions.

**Comment by forsartis** [comment]
Main release now installs Tailwindcss v1.0
