### ISSUE TITLE
Set purge inside "tailwind.config.js"

### ISSUE THREAD

**Issue by YangAi** [forsartis/vue-cli-plugin-tailwind#21]
Hello, Thanks for the plugin! It save me a lot of time. But I realized the purgecss will affect framework outside tailwind, like "vuetify".

Can I use the purge setting directly in the `tailwind.config.js`, do something like this?
```
// tailwind.config.js
 module.exports = {
//  purge: [],
  purge: [
   './public/**/*.html',
   './src/**/*.vue',
  ],
   theme: {
     extend: {},
   },
   variants: {},
   plugins: [],
 };
```

**Comment by forsartis** [comment]
Hello, yes you can do that. But you also need to remove `'vue-cli-plugin-tailwind/purgecss': {},` in your `postcss.config.js ` to disable this plugin purgecss and only use tailwinds internal one.
