### ISSUE TITLE
Tailwind is not purging unused styles because no template paths have been provided

### ISSUE THREAD

**Issue by webmasterslava** [forsartis/vue-cli-plugin-tailwind#23]
Getting the following error on the clean install of `vue-cli` and `minimal` tailwind config:
```
warn - Tailwind is not purging unused styles because no template paths have been provided.
warn - If you have manually configured PurgeCSS outside of Tailwind or are deliberately not removing unused styles, set `purge: false` in your Tailwind config file to silence this warning.
warn - https://tailwindcss.com/docs/controlling-file-size/#removing-unused-css
```

**Comment by forsartis** [comment]
Hello, you can set `purge: false` in your Tailwind config because this plugin has PurgeCSS configured outside of Tailwind.
In an upcoming version, I plan to switch to Tailwind's internal PurgeCSS setup.

**Comment by byshine** [comment]
It's not purging at all for me.

**Comment by forsartis** [comment]
The plugin now uses Tailwind's internal PurgeCSS setup.
