### ISSUE TITLE
PostCSS issues

### ISSUE THREAD

**Issue by jdfwarrior** [forsartis/vue-cli-plugin-tailwind#25]
Getting an error that PostCSS plugin tailwindcss requires PostCSS 8. The current package.json lists ^7 for PostCSS. Should this be updated?

**Comment by forsartis** [comment]
No, Vue CLI doesn't support PostCSS 8 yet. Therefore this plugin installs the [PostCSS 7 compatibility build](https://tailwindcss.com/docs/installation#post-css-7-compatibility-build) of Tailwind.
Can you check which tailwindcss version is installed? Should be `tailwindcss@2.0.1-compat`.
Maybe you installed tailwindcss manually via npm? Then running `npm uninstall tailwindcss` might solve the issue.

**Comment by jdfwarrior** [comment]
I had indeed manually updated tailwind at some point. I removed it and attempted to `npm i -D vue-cli-plugin-tailwind@latest` to update the current installation again and am back at 

`Module` build failed (from ./node_modules/postcss-loader/src/index.js):
Error: Loading PostCSS Plugin failed: Cannot find module 'vue-cli-plugin-tailwind/purgecss'`

**Comment by forsartis** [comment]
Can you post full error message?
There must be another `'vue-cli-plugin-tailwind/purgecss'` import somewhere else. Maybe in `package.json` or in a `.postcssrc` file.

**Comment by SimonPrague** [comment]
I have the same problem:
```Error: Loading PostCSS Plugin failed: Cannot find module 'vue-cli-plugin-tailwind/purgecss'```

Vue 3, Vue Cli, Typescript and Tailwind 2.0

Still can't make it work after the upgrade to Tailwind 2 ...

**Comment by forsartis** [comment]
You need to remove the whole `vue-cli-plugin-tailwind/purgecss` block and configure PurgeCSS in your `tailwind.config.js` [https://tailwindcss.com/docs/optimizing-for-production#removing-unused-css](https://tailwindcss.com/docs/optimizing-for-production#removing-unused-css)

**Comment by SimonPrague** [comment]
Thanks, I did that but the build still fails because of:
```TypeError: getProcessedPlugins is not a function```
https://github.com/tailwindlabs/tailwindcss/issues/2810
