### ISSUE TITLE
Generating tailwind.config.js does not work under macOS 

### ISSUE THREAD

**Issue by TimoZacherl** [forsartis/vue-cli-plugin-tailwind#26]
As mentioned in the title, generating the tailwind.config.js (full and minimal) does not work under macOS (Big Sur).
Made a fresh vue project and tried to install tailwind via `vue add tailwind`.

If I create a tailwind.config.js file first, it asks me to replace it. If I agree, it deletes the current tailwind.config.js, but afterwards I get the same error.

<img width="1508" alt="Bildschirmfoto 2020-11-25 um 22 17 12" src="https://user-images.githubusercontent.com/38291523/100282509-06ae6d00-2f6c-11eb-831e-bea5155e101f.png">

**Comment by omniboy** [comment]
Doesn't work on Windows either.
![image](https://user-images.githubusercontent.com/64563583/100487926-6d1dc180-310b-11eb-9193-cade3ff2b4ba.png)

**Comment by gertst** [comment]
Same here ... on a Mac

**Comment by TimoZacherl** [comment]
I've made a pull request. The problem is that, if tailwind is not already a installed dependency, the plugin can't generate the `tailwind.config.js`. As a workaround you need to install it first `npm install tailwindcss` before `vue add tailwind`.
If this is intended it should be mentioned in the README.

**Comment by forsartis** [comment]
tailwindcss should get installed automatically because it is a dependency of this plugin. 
In a fresh vue project after only running `vue add tailwind` can you check if the folder `./node_modules/tailwindcss` and the file `./node_modules/.bin/tailwind` exists? If not are those maybe nested  inside `./node_modules/vue-cli-plugin-tailwind/node_modules`?

Also, what version of node and vue-cli are you running?

**Comment by TimoZacherl** [comment]
> tailwindcss should get installed automatically because it is a dependency of this plugin.
> In a fresh vue project after only running `vue add tailwind` can you check if the folder `./node_modules/tailwindcss` and the file `./node_modules/.bin/tailwind` exists? If not are those maybe nested inside `./node_modules/vue-cli-plugin-tailwind/node_modules`?
> 
> Also, what version of node and vue-cli are you running?

I updated vue-cli (now 4.5.9) earlier today.
I can confirm that it works with this version of vue-cli, in my case at least. 
I think it was a problem with the version of vue-cli I had installed before.

**Comment by adrikagupta** [comment]
> > tailwindcss should get installed automatically because it is a dependency of this plugin.
> > In a fresh vue project after only running `vue add tailwind` can you check if the folder `./node_modules/tailwindcss` and the file `./node_modules/.bin/tailwind` exists? If not are those maybe nested inside `./node_modules/vue-cli-plugin-tailwind/node_modules`?
> > Also, what version of node and vue-cli are you running?
> 
> I updated vue-cli (now 4.5.9) earlier today.
> I can confirm that it works with this version of vue-cli, in my case at least.
> I think it was a problem with the version of vue-cli I had installed before.

I am having the same issue even though the version that I am using is also @vue/cli 4.5.9
