### ISSUE TITLE
vue-cli install not working with Vue3 + TypeScript

### ISSUE THREAD

**Issue by TheDutchCoder** [forsartis/vue-cli-plugin-tailwind#28]
When adding the plugin through vue-cli, when it finishes it'll throw errors:
![image](https://user-images.githubusercontent.com/1668207/100796688-05a79080-33ef-11eb-8cc9-ab8a3e00d840.png)

**Comment by ryanw3b3r** [comment]
I have the same issue!

**Comment by forsartis** [comment]
This is a linting error and TailwindCSS doesn't support TypeScript as far as I know. As a workaround you can disable eslint for the require statement.
```js
/* eslint-disable-next-line */
const colors = require('tailwindcss/colors')
```
