### ISSUE TITLE
@tailwind base vs @tailwind preflight

### ISSUE THREAD

**Issue by franciscolourenco** [forsartis/vue-cli-plugin-tailwind#3]
This plugin creates a tailwind.css file which imports base, but the documentation imports preflight.

https://tailwindcss.com/docs/installation/
https://github.com/tailwindcss/tailwindcss/blob/master/tailwind.css

**Comment by forsartis** [comment]
Thanks! I pushed the wrong file to npm. Should be fixed in v0.4.3

**Comment by franciscolourenco** [comment]
works, thanks!
