### ISSUE TITLE
PostCSS plugin failed

### ISSUE THREAD

**Issue by nandi95** [forsartis/vue-cli-plugin-tailwind#31]
I was using the version 2.0.1 at which point it was working flawlessly.

Running an update when I get bumped to 2.0.2 I recieve the following error on vue-cli-serve:
`Error: PostCSS received undefined instead of CSS string`

I tried every version between 2.0.1 and 2.0.5 (currently the latest)

At 2.0.4 the error has changed to
`Loading PostCSS Plugin failed: Cannot find module 'tailwindcss'`

The changes to the plugin inbetween those versions can be found here:
https://github.com/forsartis/vue-cli-plugin-tailwind/commits/master/package.json

My project is a standard vue 3 project bootstrapped by vue cli with no customisation eg.:
postcss.config.js
```js
module.exports = {
    plugins: {
        tailwindcss: {},
        autoprefixer: {}
    }
};
```

**Comment by forsartis** [comment]
Hi, postcss, tailwindcss and autoprefixer should now be listed as dependencies in your package.json.
You can run `vue invoke tailwind` to add these dependencies.

**Comment by nandi95** [comment]
Hmm, it didn't fix it for some reason.
I got it working by installing them manually:
```sh
npm i -D tailwindcss@npm:@tailwindcss/postcss7-compat @tailwindcss/postcss7-compat postcss@^7 autoprefixer@^9
```

**Comment by fullstackfool** [comment]
Having the same issue, above method didn't work, managed to solve it with:

`npm install sass --save-dev`
