### ISSUE TITLE
serve not compiling tailwind new classes

### ISSUE THREAD

**Issue by arishojaei** [forsartis/vue-cli-plugin-tailwind#38]
I install `vue-cli-plugin-tailwind` with a minimal config, when I run `yarn serve` to use `vue-cli-service serve`, new tailwind classes that I add to my code don't compile after `vue-cli-service serve` update my served project.

For example, in the below picture, you see I have `text-white`, but the button text color doesn't change to white
![Screen Shot 2021-08-15 at 11 17 10](https://user-images.githubusercontent.com/4179565/129469754-5c40da15-97a8-458c-8b36-b4f35c59f5c2.png)

**If I kill the server and run `yarn serve` again, button text changes to white**

**Comment by faithfulojebiyi** [comment]
This is because the version of tailwind did not support JIT mode. #39 this pull request fixes those issues and it supports the latest version of tailwind, meaning JIT mode is fully supported.
