### ISSUE TITLE
@apply in scss

### ISSUE THREAD

**Issue by franciscolourenco** [forsartis/vue-cli-plugin-tailwind#4]
This is unrelated to this plugin and a problem with Vetur, but do you know of any solution to allow @directives to not be flagged by the syntax highlight?

Thanks!
<img width="297" alt="Screen Shot 2019-03-28 at 18 11 44" src="https://user-images.githubusercontent.com/208149/55178088-06514380-5185-11e9-8f0a-f42354aec5c5.png">

**Comment by forsartis** [comment]
No sorry, have you seen this https://github.com/vuejs/vetur/issues/926

**Comment by franciscolourenco** [comment]
I did. It doesn't apply only to `@apply` though. Any directive gets flagged. If there was a way to get vetur to use https://marketplace.visualstudio.com/items?itemName=macieklad.tailwind-sass-syntax instead..
