### ISSUE TITLE
Vue CLI 5 beta results in "Error: PostCSS plugin postcss-discard-comments requires PostCSS 8."

### ISSUE THREAD

**Issue by lloydjatkinson** [forsartis/vue-cli-plugin-tailwind#40]
Reproduction:

Install latest version of Vue CLI (https://github.com/vuejs/vue-cli/releases)

```
vue create my-app
<pick settings>

npm run build <- Builds OK
vue add tailwind
<pick minimal>

npm run build
⠙  Building for production...

 ERROR  Failed to compile with 1 error                                                                          12:46:33

 error  in css/app.642f50fd.css

css/app.642f50fd.css from Css Minimizer plugin
Error: PostCSS plugin postcss-discard-comments requires PostCSS 8.
```

How do we fix this? Following this guide does not resolve the error: https://tailwindcss.com/docs/installation#post-css-7-compatibility-build

**Comment by forsartis** [comment]
I published a pre-release for vue-cli v5.0 and Tailwind CSS v3.0 support. See [v3.0.0-beta.0](https://github.com/forsartis/vue-cli-plugin-tailwind/releases/tag/v3.0.0-beta.0) for instructions.
