### ISSUE TITLE
Errors thrown at build

### ISSUE THREAD

**Issue by hungry4capital** [forsartis/vue-cli-plugin-tailwind#49]
Not sure if I have a special circumstance, however, when running a "vue create" (version 5 cli) project with a "vue 3" preset and "vue add tailwind", my build fails at the build script. 

Error: PostCSS plugin postcss-discard-comments requires PostCSS 8.

Anyone can explain or have also run into this problem?

(PS. I'm still relatively new)

**Comment by forsartis** [comment]
Because vue-cli v5 is still in beta, you need to run `vue add tailwind@next` 
https://github.com/forsartis/vue-cli-plugin-tailwind/issues/40#issuecomment-991896928
