### ISSUE TITLE
When will 3.0 release version be?

### ISSUE THREAD

**Issue by amoslai5128** [forsartis/vue-cli-plugin-tailwind#51]
Thanks for the amazing plugin for tailwind CSS and I love it very much.

Meanwhile, when will the 3.0 release version be? it's been a while since the launch of the pre-release `v3.0.0-beta.0`, is it stable for production for using this beta version?

Thanks.

**Comment by forsartis** [comment]
Thanks for the reminder. 
I wanted to wait until **Vue CLI v5** is out of beta. Since this is the case now, I released [v3.0.0 ](https://github.com/forsartis/vue-cli-plugin-tailwind/releases/tag/v3.0.0).

**Comment by amoslai5128** [comment]
Thanks, I'll check it out.

**Comment by lorand-horvath** [comment]
@forsartis This issue may be closed.
