### ISSUE TITLE
Does not generate tailwind.config.js

### ISSUE THREAD

**Issue by coderpradp** [forsartis/vue-cli-plugin-tailwind#7]
As mentioned in title the plugin does not generate tailwind.config.js despite choosing minimal or full option. 
I added the plugin to a fresh project generated by vue-cli 3 with default options.

![image](https://user-images.githubusercontent.com/20035221/62926722-c8238c00-bdd4-11e9-9929-96e06602b22d.png)

**Comment by forsartis** [comment]
Thanks! Are you on Windows?

**Comment by coderpradp** [comment]
Yeah I'm on Windows.

**Comment by forsartis** [comment]
Should be fixed in v1.1.0 let me know if it's still not working for you.
