### ISSUE TITLE
Can't add regex (whitelistPatterns) to package.json

### ISSUE THREAD

**Issue by sunscreem** [forsartis/vue-cli-plugin-tailwind#8]
In my `package.json`, I'm trying to prevent postcss from auto-removing a bunch of vendor css.

```
  "postcss": {
    "plugins": {
      "tailwindcss": {},
      "vue-cli-plugin-tailwind/purgecss": {
        "whitelistPatterns": ["/^ais-/"]
      },
      "autoprefixer": {}
    }
  },
```

This doesn't work as I get an npm error when I run npm run build (v.test is not a function).

If I try this:

```
  "postcss": {
    "plugins": {
      "tailwindcss": {},
      "vue-cli-plugin-tailwind/purgecss": {
        "whitelistPatterns": [/^ais-/]
      },
      "autoprefixer": {}
    }
  },
```
then npm throws an error saying its not valid json.

I'm kinda stuck on what to try next.

**Comment by forsartis** [comment]
Currently purgecss does not support regex in `package.json`, related issue https://github.com/FullHuman/purgecss/issues/177. 

But you can configure purgecss via a dedicated `postcss.config.js`

```javascript
module.exports = {
  plugins: {
    tailwindcss: {},
    'vue-cli-plugin-tailwind/purgecss': {
      whitelistPattern: [/^ais-/],
    },
    autoprefixer: {},
  },
};
```

**Comment by sunscreem** [comment]
Awesome - thank you @forsartis. 

My issue now is that I can't seem to get vuecli to play nicely with a postcss.config.js

I'll work that one separately.

**Comment by sunscreem** [comment]
All sorted .. I needed to delete the "postcss" section in my package.json.
